"""external registration flag and template run order

Revision ID: 29338e5310b1
Revises: febf1477c166
Create Date: 2026-09-19 15:57:47.140841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29338e5310b1'
down_revision = 'febf1477c166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_template_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_index', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_external', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('registration_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_external', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('registration_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registration_url')
        batch_op.drop_column('registration_external')

    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.drop_column('registration_url')
        batch_op.drop_column('registration_external')

    with op.batch_alter_table('event_template_runs', schema=None) as batch_op:
        batch_op.drop_column('sort_index')

    # ### end Alembic commands ###
