"""add event templates

Revision ID: 33d169664153
Revises: zc2d3e4f5a6b
Create Date: 2026-09-19 15:35:40.830620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d169664153'
down_revision = 'zc2d3e4f5a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_event_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('day_count', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('special_ruleset', sa.String(length=50), nullable=True),
    sa.Column('organiser_club_id', sa.Integer(), nullable=True),
    sa.Column('pruefungsleiter', sa.String(length=255), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('allows_bitches_in_season', sa.Boolean(), nullable=False),
    sa.Column('bitches_in_season_start_last', sa.Boolean(), nullable=False),
    sa.Column('ring_count', sa.Integer(), nullable=False),
    sa.Column('notes_public', sa.Text(), nullable=True),
    sa.Column('startnumber_schema', sa.Text(), nullable=True),
    sa.Column('run_time_config', sa.Text(), nullable=True),
    sa.Column('ring_start_times', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_template_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=5), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['event_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'run_type', 'category', 'class_level', 'is_final', name='uq_event_template_run')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_template_runs')
    op.drop_table('event_templates')
    # ### end Alembic commands ###
