"""initial schema

Revision ID: 68c4313ed176
Revises: 
Create Date: 2026-04-12 22:39:48.554568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c4313ed176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vereinsnummer', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vereinsnummer')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('license_no', sa.String(length=50), nullable=False),
    sa.Column('license_kind', sa.Enum('CH', 'FOREIGN', name='license_kind'), nullable=False),
    sa.Column('foreign_country_code', sa.String(length=3), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('tka_master_status', sa.Enum('PENDING', 'IN_EXPORT', 'OK', 'ISSUE', 'NOT_REQUIRED', name='tka_master_status'), nullable=False),
    sa.Column('tka_category_confirmed', sa.String(length=20), nullable=True),
    sa.Column('tka_master_checked_at', sa.DateTime(), nullable=True),
    sa.Column('tka_issue_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('license_no')
    )
    op.create_table('judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ais_judge_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ais_judge_id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('asmv_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('kategorie', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('dog_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='authorization_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CO_OWNER', 'HANDLER', name='dog_owner_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('ais_turniernummer', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('special_ruleset', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('organiser_club_id', sa.Integer(), nullable=True),
    sa.Column('pruefungsleiter', sa.String(length=255), nullable=True),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('judge2_id', sa.Integer(), nullable=True),
    sa.Column('allows_bitches_in_season', sa.Boolean(), nullable=False),
    sa.Column('is_breed_restricted', sa.Boolean(), nullable=False),
    sa.Column('registration_open_at', sa.DateTime(), nullable=True),
    sa.Column('registration_close_at', sa.DateTime(), nullable=True),
    sa.Column('lizenzcheck_done_at', sa.DateTime(), nullable=True),
    sa.Column('results_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('billing_mode', sa.Enum('PORTAL', 'ORGANIZER', name='billing_mode'), nullable=False),
    sa.Column('billing_notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('startlist_public', sa.Boolean(), nullable=False),
    sa.Column('schedule_public', sa.Boolean(), nullable=False),
    sa.Column('results_public', sa.Boolean(), nullable=False),
    sa.Column('start_numbers_locked', sa.Boolean(), nullable=False),
    sa.Column('start_numbers_generated_at', sa.DateTime(), nullable=True),
    sa.Column('start_numbers_rule_set', sa.Text(), nullable=True),
    sa.Column('schedule_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['judge2_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['organiser_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ais_turniernummer'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asmv_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['asmv_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'person_id', name='uq_asmv_team_person')
    )
    op.create_table('exchange_export_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('schema', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_external_id', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=True),
    sa.Column('source_device', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_external_id', 'source_device', 'sequence_no', name='uq_live_updates_event_device_seq')
    )
    with op.batch_alter_table('live_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_updates_event_external_id'), ['event_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_updates_source_device'), ['source_device'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('club_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'CONFIRMED', 'CANCELLED', name='registration_status'), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('tka_event_check_status', sa.Enum('PENDING', 'IN_EXPORT', 'OK', 'ISSUE', 'CLASS_CHANGED', 'AUTO_OK', name='tka_event_check_status'), nullable=False),
    sa.Column('verified_license_no', sa.String(length=50), nullable=True),
    sa.Column('verified_category_code', sa.String(length=20), nullable=True),
    sa.Column('verified_class_level', sa.Integer(), nullable=True),
    sa.Column('verified_dog_name', sa.String(length=120), nullable=True),
    sa.Column('tka_issue_type', sa.Enum('DATA_MISMATCH', 'LICENSE_UNKNOWN', 'LICENSE_INVALID', 'PARSER_UNKNOWN_FORMAT', name='tka_issue_type'), nullable=True),
    sa.Column('tka_issue_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category_code in ('Small','Medium','Intermediate','Large')", name='ck_registrations_category_code'),
    sa.CheckConstraint('class_level in (1, 2, 3)', name='ck_registrations_class_level'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['handler_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('result_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('schema', sa.String(length=100), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('final', sa.Boolean(), nullable=False),
    sa.Column('zip_path', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ring', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('discipline', sa.String(length=20), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("category_code in ('Small','Medium','Intermediate','Large')", name='ck_schedule_blocks_category_code'),
    sa.CheckConstraint('class_level in (1, 2, 3)', name='ck_schedule_blocks_class_level'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_blocks_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_blocks_sort_index'), ['sort_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_blocks_start_at'), ['start_at'], unique=False)

    op.create_table('tka_export_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.Enum('MASTER_CHECK', 'EVENT_CHECK', name='tka_export_type'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_import_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_import_id'], ['result_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_import_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ring', sa.String(length=50), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('category_code', sa.String(length=20), nullable=True),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('run_no', sa.Integer(), nullable=True),
    sa.Column('registration_external_id', sa.String(length=64), nullable=True),
    sa.Column('start_no', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time_s', sa.Float(), nullable=True),
    sa.Column('faults', sa.Integer(), nullable=True),
    sa.Column('refusals', sa.Integer(), nullable=True),
    sa.Column('eliminated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dog_name', sa.String(length=120), nullable=True),
    sa.Column('handler_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['result_import_id'], ['result_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_registration_external_id'), ['registration_external_id'], unique=False)

    op.create_table('start_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('start_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'registration_id', name='uq_start_numbers_event_reg'),
    sa.UniqueConstraint('event_id', 'start_no', name='uq_start_numbers_event_start_no')
    )
    op.create_table('tka_export_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('license_no', sa.String(length=50), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['tka_export_batches.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tka_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('imported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['tka_export_batches.id'], ),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tka_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tka_import_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('license_no', sa.String(length=50), nullable=True),
    sa.Column('finding_kind', sa.Enum('CLASS_OR_CATEGORY_MISMATCH', 'LICENSE_UNKNOWN', 'LICENSE_INVALID', 'UNKNOWN_FORMAT', name='tka_finding_kind'), nullable=False),
    sa.Column('issue_type', sa.Enum('DATA_MISMATCH', 'LICENSE_UNKNOWN', 'LICENSE_INVALID', 'PARSER_UNKNOWN_FORMAT', name='tka_issue_type'), nullable=False),
    sa.Column('import_category_code', sa.String(length=20), nullable=True),
    sa.Column('import_class_level', sa.Integer(), nullable=True),
    sa.Column('system_category_code', sa.String(length=20), nullable=True),
    sa.Column('system_class_level', sa.Integer(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['tka_import_id'], ['tka_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tka_findings')
    op.drop_table('tka_imports')
    op.drop_table('tka_export_rows')
    op.drop_table('start_numbers')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_registration_external_id'))

    op.drop_table('results')
    op.drop_table('documents')
    op.drop_table('tka_export_batches')
    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_start_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_sort_index'))
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_event_id'))

    op.drop_table('schedule_blocks')
    op.drop_table('result_imports')
    op.drop_table('registrations')
    with op.batch_alter_table('live_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_updates_source_device'))
        batch_op.drop_index(batch_op.f('ix_live_updates_event_external_id'))

    op.drop_table('live_updates')
    op.drop_table('exchange_export_logs')
    op.drop_table('asmv_team_members')
    op.drop_table('users')
    op.drop_table('events')
    op.drop_table('dog_owners')
    op.drop_table('dog_authorizations')
    op.drop_table('asmv_teams')
    op.drop_table('people')
    op.drop_table('judges')
    op.drop_table('dogs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
