"""add reservation and website fields to event templates

Revision ID: febf1477c166
Revises: 33d169664153
Create Date: 2026-09-19 15:45:35.290805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febf1477c166'
down_revision = '33d169664153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_description_de', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reservation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('option_special_eval', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('option_website', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('option_event_support', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.drop_column('option_event_support')
        batch_op.drop_column('option_website')
        batch_op.drop_column('option_special_eval')
        batch_op.drop_column('reservation_notes')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('event_description_de')

    # ### end Alembic commands ###
